version: "3.9"
services:
  app:
    restart: always 
    image: "nsmv/jiseki-web:latest"
    ports:
      - "10083:8080"
    volumes:
      - /opt/logs/jiseki:/usr/local/tomcat/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
